package model.beans;
// Generated 21/05/2020 11:37:51 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Funcionario generated by hbm2java
 */
public class Funcionario  implements java.io.Serializable {


     private Integer funId;
     private String funNome;
     private String funUsuario;
     private String funSenha;
     private Set vendas = new HashSet(0);

    public Funcionario() {
    }

	
    public Funcionario(String funNome, String funUsuario, String funSenha) {
        this.funNome = funNome;
        this.funUsuario = funUsuario;
        this.funSenha = funSenha;
    }
    public Funcionario(String funNome, String funUsuario, String funSenha, Set vendas) {
       this.funNome = funNome;
       this.funUsuario = funUsuario;
       this.funSenha = funSenha;
       this.vendas = vendas;
    }
   
    public Integer getFunId() {
        return this.funId;
    }
    
    public void setFunId(Integer funId) {
        this.funId = funId;
    }
    public String getFunNome() {
        return this.funNome;
    }
    
    public void setFunNome(String funNome) {
        this.funNome = funNome;
    }
    public String getFunUsuario() {
        return this.funUsuario;
    }
    
    public void setFunUsuario(String funUsuario) {
        this.funUsuario = funUsuario;
    }
    public String getFunSenha() {
        return this.funSenha;
    }
    
    public void setFunSenha(String funSenha) {
        this.funSenha = funSenha;
    }
    public Set getVendas() {
        return this.vendas;
    }
    
    public void setVendas(Set vendas) {
        this.vendas = vendas;
    }




}


