package model.beans;
// Generated 21/05/2020 11:37:51 by Hibernate Tools 4.3.1



/**
 * Itemvenda generated by hbm2java
 */
public class Itemvenda  implements java.io.Serializable {


     private Integer itvId;
     private Prodserv prodserv;
     private Venda venda;
     private int itvQuant;
     private double itvSubtotal;

    public Itemvenda() {
    }

    public Itemvenda(Prodserv prodserv, Venda venda, int itvQuant, double itvSubtotal) {
       this.prodserv = prodserv;
       this.venda = venda;
       this.itvQuant = itvQuant;
       this.itvSubtotal = itvSubtotal;
    }
   
    public Integer getItvId() {
        return this.itvId;
    }
    
    public void setItvId(Integer itvId) {
        this.itvId = itvId;
    }
    public Prodserv getProdserv() {
        return this.prodserv;
    }
    
    public void setProdserv(Prodserv prodserv) {
        this.prodserv = prodserv;
    }
    public Venda getVenda() {
        return this.venda;
    }
    
    public void setVenda(Venda venda) {
        this.venda = venda;
    }
    public int getItvQuant() {
        return this.itvQuant;
    }
    
    public void setItvQuant(int itvQuant) {
        this.itvQuant = itvQuant;
    }
    public double getItvSubtotal() {
        return this.itvSubtotal;
    }
    
    public void setItvSubtotal(double itvSubtotal) {
        this.itvSubtotal = itvSubtotal;
    }




}


