package model.beans;
// Generated 21/05/2020 11:37:51 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Prodserv generated by hbm2java
 */
public class Prodserv  implements java.io.Serializable {


     private Integer proId;
     private String proDescricao;
     private String proTipo;
     private double proPrecoCusto;
     private double proPrecoVenda;
     private int proQuantEstoque;
     private Set itemvendas = new HashSet(0);

    public Prodserv() {
    }

	
    public Prodserv(String proDescricao, String proTipo, double proPrecoCusto, double proPrecoVenda, int proQuantEstoque) {
        this.proDescricao = proDescricao;
        this.proTipo = proTipo;
        this.proPrecoCusto = proPrecoCusto;
        this.proPrecoVenda = proPrecoVenda;
        this.proQuantEstoque = proQuantEstoque;
    }
    public Prodserv(String proDescricao, String proTipo, double proPrecoCusto, double proPrecoVenda, int proQuantEstoque, Set itemvendas) {
       this.proDescricao = proDescricao;
       this.proTipo = proTipo;
       this.proPrecoCusto = proPrecoCusto;
       this.proPrecoVenda = proPrecoVenda;
       this.proQuantEstoque = proQuantEstoque;
       this.itemvendas = itemvendas;
    }
   
    public Integer getProId() {
        return this.proId;
    }
    
    public void setProId(Integer proId) {
        this.proId = proId;
    }
    public String getProDescricao() {
        return this.proDescricao;
    }
    
    public void setProDescricao(String proDescricao) {
        this.proDescricao = proDescricao;
    }
    public String getProTipo() {
        return this.proTipo;
    }
    
    public void setProTipo(String proTipo) {
        this.proTipo = proTipo;
    }
    public double getProPrecoCusto() {
        return this.proPrecoCusto;
    }
    
    public void setProPrecoCusto(double proPrecoCusto) {
        this.proPrecoCusto = proPrecoCusto;
    }
    public double getProPrecoVenda() {
        return this.proPrecoVenda;
    }
    
    public void setProPrecoVenda(double proPrecoVenda) {
        this.proPrecoVenda = proPrecoVenda;
    }
    public int getProQuantEstoque() {
        return this.proQuantEstoque;
    }
    
    public void setProQuantEstoque(int proQuantEstoque) {
        this.proQuantEstoque = proQuantEstoque;
    }
    public Set getItemvendas() {
        return this.itemvendas;
    }
    
    public void setItemvendas(Set itemvendas) {
        this.itemvendas = itemvendas;
    }




}


